global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090

  - job_name: "cassandra"
    scrape_interval: 15s
    scrape_timeout:  15s
    static_configs:
      - targets:
        - 195.148.21.10:7199
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
  
  - job_name: 'vernemq-gcp-edge-1'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: 
        - 35.198.150.147:8888

  
  - job_name: 'vernemq-gcp-edge-2'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: 
        - 35.240.4.246:8888

  
  - job_name: 'kafka-csc-cloud'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: 
        - 195.148.20.12:7071
